import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// We need to include the base CSS in the root of
// the app so all of our components can inherit the styles
import { Button, Table } from '@neo4j-ndl/react';

import { useReactTable } from '@tanstack/react-table';
import "@neo4j-ndl/base/lib/neo4j-ds-styles.css";
import { CommonTableParam, COMMON_TABLE_PROPS } from './common';


export const parameters ={
  title: 'Tables/Simple Table',
  component: Button,
  parameters: CommonTableParam,
};

export default function tablepage() {
  return (
    <>
      <Head>
        <title>A Tables</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {Array.from(Array(100)).map((_, i) => {
         const table = useReactTable({
          ...COMMON_TABLE_PROPS,
        });
         return <Table className={styles.table} key={i} resizable={false} tableProps={table} />

        })}
      </main>
    </>
  )
}

