import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// We need to include the base CSS in the root of
// the app so all of our components can inherit the styles
import Alert from '@mui/material/Alert';

export default function bannerpage() {
  return (
    <>
      <Head>
        <title>A Banner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Alert 
          severity="error"
          className='kickAsBanner'
        >
          This is an error alert — check it out!
        </Alert>
      </main>
    </>
  )
}

