import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// We need to include the base CSS in the root of
// the app so all of our components can inherit the styles
import '@neo4j-ndl/base/lib/neo4j-ds-styles.css';
import Button from '@mui/material/Button';
// import { Button } from '@neo4j-ndl/react';

export default function buttonpage() {
  // const renderShowMoreButton = () => (
  //   <Button
  //     size='small'
  //     color='primary'
  //     fill='text'
  //     type='button'
  //   >
  //     a very nie button
  //   </Button>
  // )
  return (
    <>
      <Head>
        <title>A Button</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button className="basicbutton">test</Button>
      </main>
    </>
  )
}

