import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// We need to include the base CSS in the root of
// the app so all of our components can inherit the styles
import { Button, IconButton } from "@neo4j-ndl/react";
import { HeartIconOutline  } from '@neo4j-ndl/react/icons';
import "@neo4j-ndl/base/lib/neo4j-ds-styles.css";

export default function buttonpage() {
  return (
    <>
      <Head>
        <title>A Button</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Button 
          className="basicbutton-filled"
          color="success"
          fill="filled"
          size="large"
          type="button"
        >
          test
        </Button>
        <Button 
          className="basicbutton-text"
          color="neutral"
          fill="text"
          size="small"
          type="button"
        >
          test
        </Button>
        <Button
          arial-label="Search Icon"
          className="basicbutton-outlined"
          color="warning"
          fill="outlined"
          size="medium"
          type="submit"
        >
          test
        </Button>
        <IconButton arial-label="Search Icon" className='test' clean size='small'>
          <HeartIconOutline />
        </IconButton>
      </main>
    </>
  )
}

