import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// We need to include the base CSS in the root of
// the app so all of our components can inherit the styles
import { CodeBlock } from "@neo4j-ndl/react";
import "@neo4j-ndl/base/lib/neo4j-ds-styles.css";

export default function codeblockpage() {
  return (
    <>
      <Head>
        <title>A CodeBlock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.codeblockwrapper}>
          {Array.from(Array(100)).map((_, i) => (
            <CodeBlock
              key={i}
              actions={[
                {
                  'aria-label': 'copy',
                  children: <div className="n-text-light-neutral-text-weak" />,
                  onClick: function $a(){},
                  title: 'copy'
                },
                {
                  'aria-label': 'run',
                  children: <p className="n-text-primary-50" />,
                  onClick: function $a(){},
                  title: 'run'
                }
              ]}
              code="
                import { tokens as ndsTokens } from '@neo4j-ndl/tokens';IamtestingsoIGetOverflowonTheHorizontalAxis
                import { tokens as ndsTokens } from '@neo4j-ndl/tokens';IamtestingsoIGetOverflowonTheHorizontalAxis
                import { tokens as ndsTokens } from '@neo4j-ndl/tokens';IamtestingsoIGetOverflowonTheHorizontalAxis
                import { tokens as ndsTokens } from '@neo4j-ndl/tokens';IamtestingsoIGetOverflowonTheHorizontalAxis
              "
              headerTitle="Header"
              language="javascript"
              maxHeight={320}
              theme="vs"
              className={styles.kickAsCodeBlock}
            />
          ))}
        </div>
      </main>
    </>
  )
}

