import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/report.module.scss'
// import results from '../../results.json'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Performance test suite for ndl</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Accessibility testing the ndl project!</h1>
        <p className={styles.description}>We are trying the bust ndl  </p>
        <div>
          <ul>
            <li className={styles.list}>
              <a className={styles.link} href="/banner">Banner</a>
              <a className={styles.link} href="/button">Button</a>
              <a className={styles.link} href="/checkbox">Checkbox</a>
              <a className={styles.link} href="/codeblock">Codeblock</a>
              <a className={styles.link} href="/dialog">Dialog</a>
              <a className={styles.link} href="/label">Label</a>
              <a className={styles.link} href="/modal">Modal</a>
              <a className={styles.link} href="/sitenavigation">Side Navigation</a>
              <a className={styles.link} href="/spinner">Progress Spinner</a>
              <a className={styles.link} href="/textinput">Text input</a>
              <a className={styles.link} href="/tooltip">Tooltip</a>
            </li>
          </ul>         
        </div>
      </main>
    </>
  )
}
