import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// We need to include the base CSS in the root of
// the app so all of our components can inherit the styles
import { Button, Modal, DragAndDrop } from "@neo4j-ndl/react";
import "@neo4j-ndl/base/lib/neo4j-ds-styles.css";
import React from 'react';

export default function labelpage() {
  const [ismodalopen, setOpen] = React.useState(false);
  function handleOpen() {
    setOpen(true);
  }

  function handleClose() {
    setOpen(false);
  }

  return (
    <>
      <Head>
        <title>A Modal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div
        className="n-flex n-flex-col n-items-center n-justify-center"
        style={{
          height: '400px'
        }}
      >
        <React.Fragment key=".0">
          <div className="n-flex n-justify-center">
            <Button onClick={handleOpen}>
              Click Me!
            </Button>
          </div>
          <Modal
            className="n-p-2 n-bg-neutral-10 n-rounded-lg"
            id="default-menu"
            onClose={handleOpen}
            open={ismodalopen}
          >
            <DragAndDrop dropZoneOptions={{}} />
          </Modal>
        </React.Fragment>
      </div>
      </main>
    </>
  )
}

