import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// We need to include the base CSS in the root of
// the app so all of our components can inherit the styles
import { Radio } from "@neo4j-ndl/react";
import "@neo4j-ndl/base/lib/neo4j-ds-styles.css";

export default function radiopage() {
  return (
    <>
      <Head>
        <title>A Radio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Radio</h1>
        <Radio label="Radio label" />
        <Radio
          aria-label="example aria label"
          label={<div style={{background: '#FFB8C4'}}>Custom label</div>}
        />
      </main>
    </>
  )
}

