import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// We need to include the base CSS in the root of
// the app so all of our components can inherit the styles
import { SideNavigation, SideNavigationList, SideNavigationGroupHeader, SideNavigationItem } from "@neo4j-ndl/react";
import "@neo4j-ndl/base/lib/neo4j-ds-styles.css";
import React, { useState } from 'react';

export default function Sidenavigationpage() {
  const [isNavigationOpen, setIsNavigationOpen] = useState(false);

  function handleOpen() {
    setIsNavigationOpen(true);
  }

  function handleClose() {
    setIsNavigationOpen(false);
  }

  return (
    <>
      <Head>
        <title>A Modal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div
          style={{
            display: 'flex',
            height: 'calc(40vh - 32px)',
            minHeight: '700px'
          }}
        >
          <SideNavigation
            expanded={isNavigationOpen}
            onExpandedChange={setIsNavigationOpen}
            position="left"
          >
            <SideNavigationList>
              <SideNavigationGroupHeader>AuraDB</SideNavigationGroupHeader>
              <SideNavigationItem href="#" onClick={handleClose} selected>
                Instances
              </SideNavigationItem>
              <SideNavigationItem href="#" onClick={handleClose}>
                Connect
              </SideNavigationItem>
              <SideNavigationList>
                <SideNavigationItem href="#" onClick={handleClose}>
                  Python
                </SideNavigationItem>
                <SideNavigationItem href="#" onClick={handleClose}>
                  JavaScript
                </SideNavigationItem>
              </SideNavigationList>
              <SideNavigationGroupHeader>AuraDS</SideNavigationGroupHeader>
              <SideNavigationList>
                <SideNavigationItem href="#" onClick={handleClose}>
                  Instances
                </SideNavigationItem>
                <SideNavigationItem href="#" onClick={handleClose}>
                  Getting Started
                </SideNavigationItem>
              </SideNavigationList>
            </SideNavigationList>
          </SideNavigation>
          <div className={styles.content}>Content</div>
        </div>
      </main>
    </>
  );
}


