import Head from 'next/head'
import styles from '@/styles/Home.module.css'
// We need to include the base CSS in the root of
// the app so all of our components can inherit the styles
import { Tooltip } from "@neo4j-ndl/react";
import "@neo4j-ndl/base/lib/neo4j-ds-styles.css";

export default function tooltippage() {
  return (
    <>
      <Head>
        <title>A Button</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Tooltip</h1>
        <Tooltip
          arrowPosition="bottom"
          style={{
            maxWidth: '150px'
          }}
        >
          Some useful extra information about a thing
        </Tooltip>
      </main>
    </>
  )
}

